// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: example.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TFRecordReader {

  /// <summary>Holder for reflection information generated from example.proto</summary>
  public static partial class ExampleReflection {

    #region Descriptor
    /// <summary>File descriptor for example.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExampleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1leGFtcGxlLnByb3RvEg9URlJlY29yZF9SZWFkZXIaDWZlYXR1cmUucHJv",
            "dG8iNgoHRXhhbXBsZRIrCghmZWF0dXJlcxgBIAEoCzIZLlRGUmVjb3JkX1Jl",
            "YWRlci5GZWF0dXJlcyJzCg9TZXF1ZW5jZUV4YW1wbGUSKgoHY29udGV4dBgB",
            "IAEoCzIZLlRGUmVjb3JkX1JlYWRlci5GZWF0dXJlcxI0Cg1mZWF0dXJlX2xp",
            "c3RzGAIgASgLMh0uVEZSZWNvcmRfUmVhZGVyLkZlYXR1cmVMaXN0c0KBAQoW",
            "b3JnLnRlbnNvcmZsb3cuZXhhbXBsZUINRXhhbXBsZVByb3Rvc1ABWlNnaXRo",
            "dWIuY29tL3RlbnNvcmZsb3cvdGVuc29yZmxvdy90ZW5zb3JmbG93L2dvL2Nv",
            "cmUvZXhhbXBsZS9leGFtcGxlX3Byb3Rvc19nb19wcm90b/gBAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TFRecordReader.FeatureReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TFRecordReader.Example), global::TFRecordReader.Example.Parser, new[]{ "Features" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TFRecordReader.SequenceExample), global::TFRecordReader.SequenceExample.Parser, new[]{ "Context", "FeatureLists" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Example : pb::IMessage<Example> {
    private static readonly pb::MessageParser<Example> _parser = new pb::MessageParser<Example>(() => new Example());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Example> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFRecordReader.ExampleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Example() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Example(Example other) : this() {
      features_ = other.features_ != null ? other.features_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Example Clone() {
      return new Example(this);
    }

    /// <summary>Field number for the "features" field.</summary>
    public const int FeaturesFieldNumber = 1;
    private global::TFRecordReader.Features features_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TFRecordReader.Features Features {
      get { return features_; }
      set {
        features_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Example);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Example other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Features, other.Features)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (features_ != null) hash ^= Features.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (features_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Features);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (features_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Features);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Example other) {
      if (other == null) {
        return;
      }
      if (other.features_ != null) {
        if (features_ == null) {
          Features = new global::TFRecordReader.Features();
        }
        Features.MergeFrom(other.Features);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (features_ == null) {
              Features = new global::TFRecordReader.Features();
            }
            input.ReadMessage(Features);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SequenceExample : pb::IMessage<SequenceExample> {
    private static readonly pb::MessageParser<SequenceExample> _parser = new pb::MessageParser<SequenceExample>(() => new SequenceExample());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SequenceExample> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TFRecordReader.ExampleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SequenceExample() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SequenceExample(SequenceExample other) : this() {
      context_ = other.context_ != null ? other.context_.Clone() : null;
      featureLists_ = other.featureLists_ != null ? other.featureLists_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SequenceExample Clone() {
      return new SequenceExample(this);
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 1;
    private global::TFRecordReader.Features context_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TFRecordReader.Features Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    /// <summary>Field number for the "feature_lists" field.</summary>
    public const int FeatureListsFieldNumber = 2;
    private global::TFRecordReader.FeatureLists featureLists_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TFRecordReader.FeatureLists FeatureLists {
      get { return featureLists_; }
      set {
        featureLists_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SequenceExample);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SequenceExample other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Context, other.Context)) return false;
      if (!object.Equals(FeatureLists, other.FeatureLists)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (context_ != null) hash ^= Context.GetHashCode();
      if (featureLists_ != null) hash ^= FeatureLists.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (context_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Context);
      }
      if (featureLists_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FeatureLists);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (context_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Context);
      }
      if (featureLists_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FeatureLists);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SequenceExample other) {
      if (other == null) {
        return;
      }
      if (other.context_ != null) {
        if (context_ == null) {
          Context = new global::TFRecordReader.Features();
        }
        Context.MergeFrom(other.Context);
      }
      if (other.featureLists_ != null) {
        if (featureLists_ == null) {
          FeatureLists = new global::TFRecordReader.FeatureLists();
        }
        FeatureLists.MergeFrom(other.FeatureLists);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (context_ == null) {
              Context = new global::TFRecordReader.Features();
            }
            input.ReadMessage(Context);
            break;
          }
          case 18: {
            if (featureLists_ == null) {
              FeatureLists = new global::TFRecordReader.FeatureLists();
            }
            input.ReadMessage(FeatureLists);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
